name: Manual workflow

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: windows-latest

    steps:

    - name: Find something great
      run: |
        Invoke-WebRequest https://app.fossa.com -TimeoutSec 3
        Get-ChildItem Cert:\LocalMachine\My | ft -AutoSize
        Get-PSDrive cert | ft -AutoSize
        Get-ChildItem Cert:\LocalMachine\Root\
